 -- Creación de la tabla 'beneficios' en el esquema 'public'.
-- Esta tabla almacena información sobre los beneficios, como su nombre, una imagen,
-- el estado de si está activo, y quién lo creó y cuándo.
CREATE TABLE public.beneficios (
    beneficio_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_imagen VARCHAR(250),
    nombre_beneficio VARCHAR(250) NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    apoderado_id BIGINT REFERENCES public.apoderados (apoderado_id) ON DELETE SET NULL, 
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
    actualizado_en TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Creación de un trigger para actualizar automáticamente el campo 'actualizado_en'
-- cada vez que se modifique una fila. Esto es útil para auditar los cambios.
CREATE OR REPLACE FUNCTION actualizar_timestamp_actualizado()
RETURNS TRIGGER AS $$
BEGIN
   NEW.actualizado_en = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER actualizar_beneficios_timestamp
BEFORE UPDATE ON public.beneficios
FOR EACH ROW
EXECUTE FUNCTION actualizar_timestamp_actualizado();

---
-- Creación de la tabla 'beneficios_descripcion'.
-- Esta tabla contiene detalles específicos de cada beneficio, como su precio,
-- descripción y vigencia.
CREATE TABLE public.beneficios_descripcion (
    descripcion_beneficios_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    beneficio_id BIGINT REFERENCES public.beneficios (beneficio_id) ON DELETE SET NULL, -- Se agregó la relación con la tabla 'beneficios'.
    descripcion VARCHAR(250) NOT NULL,
    precio FLOAT NOT NULL,
    es_descuento BOOLEAN DEFAULT TRUE,
    descuento_porcentaje FLOAT DEFAULT 0,
    stock INTEGER DEFAULT 0,
    vigencia_promo DATE,
    vigencia_canje DATE
);


select 